//@version=4
strategy("Moving Average Cross", overlay=true)

ema20 = ema(close, 20)
ema50 = ema(close, 50)

plot(ema20, title="20", color=#00ffaa, linewidth=3)
plot(ema50, title="50", color=#FFC11C, linewidth=2)

long = ema20 > ema50
short = ema20 < ema50

longcondition = long and long[10] and not long[11]
shortcondition = short and short[1] and not short[11]

closelong = ema20 < ema50 and not long[11]
closeshort = ema20 > ema50 and not short[11]

start = timestamp(2019,1,1)
end = timestamp(2020,12,31)

//if time >= start and time <= end
//    strategy.entry("Long", strategy.long, 1000.0, when = longcondition)
//    strategy.entry("Short", strategy.short, 1000.0, when = shortcondition)

strategy.entry("Long", strategy.long, 1000.0, when = longcondition)
strategy.entry("Short", strategy.short, 1000.0, when = shortcondition)

strategy.close("Long", when = closelong)
strategy.close("Short", when = closeshort)